name = "ssmotor-tk"
type = "webpack"
account_id = "0ded48be03f18b53d897f1e3e814570f"
workers_dev = true

[site]
bucket = "./dist/ssmotor"
entry-point = "workers-site"

[env.production]
zone_id = "fac399ac86dedad9a260b382f1555789"
route = "ssmotor.tk/*"
